trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.1.0'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'your-backend-service'
    backendAzureRmResourceGroupName: 'your-backend-rg'
    backendAzureRmStorageAccountName: 'your-backend-storage-account'
    backendAzureRmContainerName: 'your-backend-container'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceName: 'your-environment'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

